PEtab-dev/PEtab-GUI

- huiPESTO/PEtab_edit_gui/penGUI_view.py
fixes problem that occured due to #12 wrong merge
> fixed Find/replace

- src/petab_gui/views/main_view.py
- src/petab_gui/views/measurement_plot.py
This PR fixes the issue that the dock positions were not correctly saved between runs.
> Save settings of dock widgets

- src/petab_gui/app.py
- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/models/petab_model.py
- src/petab_gui/models/sbml_model.py
- src/petab_gui/utils.py
- src/petab_gui/views/logger.py
- src/petab_gui/views/table_view.py
- allows empty start
- corrected yaml upload (previously indexes were wrong)
- Check Model Button
- Automated suggestions (i can provide a list of what we are suggesting and we can discuss on this)
> Rework main model

- src/petab_gui/__main__.py
- src/petab_gui/app.py
- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/views/main_view.py
For discussion on Thu, this PR changes the gui a bit, so that files can be passed along as command line args (either model or yaml file so far) or if dropped onto the GUI
further changes on gui needed: 
- application name should list currently loaded name
- the model changes from (https://github.com/PaulJonasJost/PEtab_GUI/pull/28) should be merged in first
- new open functions should ask for save if the old model was changed
- currently there is a hack in there for the main window to prompt the controller to open a file
> Open files from command line

- pyproject.toml
- src/petab_gui/controllers/sbml_controller.py
- src/petab_gui/models/sbml_model.py
- src/petab_gui/utils.py
This PR 
*  fixes a typo in the project file (missing comma)
*  moves the utility functions to convert sbml -> ant or ant -> sbml into the util file
* adjusts the dependencies to list antimony rather than tellurium
> Fix pyproject file, only require antimony not all of tellurium

- src/petab_gui/controllers/logger_controller.py
- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/controllers/sbml_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/utils.py
- src/petab_gui/views/logger.py
- src/petab_gui/views/main_view.py
- src/petab_gui/views/task_bar.py
also Fixed Data Matrix Upload.
> Unified Upload

- src/petab_gui/controllers/mother_controller.py
As discussed, open file renamed to open, shortcut added, opens all files by default
> add shortcut to open; open all files by default

- src/petab_gui/app.py
- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/controllers/sbml_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/controllers/utils.py
- src/petab_gui/views/main_view.py
- src/petab_gui/views/task_bar.py
Added the option to add/append a table. Disabled for .yaml and .sbml files
> open_vs_add

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
Observables are only renamed if they have been in use before. Conditions are added if they get newly defined in meas table and renamed if they get changed in condition table and have seen use in meas table.
> renaming_observable

- src/petab_gui/C.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/utils.py
Enable changing of a whole column at the same time *if* only cells from a single column are selected.
To be discussed: We now have a link between model and view, as the model needs the selection model. Could perhaps be resolved via signals etc but i dont see a general problem here. It just mixes the set programming style of model/view/controller
> Column Editing

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/views/main_view.py
- src/petab_gui/views/task_bar.py
Partially or completely closes #50.
Definitely Fixes the Issue of The MAC mentioned, should also fix the one for windows through less signalling issues
> Update Closing File

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/models/petab_model.py
Resets invalid cells if petab linter succeeds or table was overwritten
> Reset Invalid Cells

- src/petab_gui/app.py
- src/petab_gui/controllers/logger_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/stylesheet.css
- src/petab_gui/views/main_view.py
- src/petab_gui/views/table_view.py
- Coloring of cells should now move with cell deletion, copy pasting and cell adding
- First Draft for a stylesheet (WIP)
> Coloring in cell editing

- src/petab_gui/models/pandas_table_model.py
Fixed a problem with the invalidation of cells and with copy paste as we are now using a proxy model.
> Copy Paste under ProxyModel

- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/views/table_view.py
> correcting_column_targeting

- src/petab_gui/app.py
- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/utils.py
- src/petab_gui/views/main_view.py
- src/petab_gui/views/table_view.py
- src/petab_gui/views/task_bar.py
Creates find/replace bar. Can be filtered on the tabs. Can be clicked through and replaced. Can all be replaced.
Discussionpoints:
1. Deactivated the stylesheet for now, as i find this nicer and the only thing i really care about are slightly colored tables. Your opinion on this? Or should there be an option to have completely blank tables?
2. Currently we just change the color of the text. Happy for suggestions on other highlighting
3. The tables are when in search all not focused, thus selected cells just are greyed out, any suggestions on improving this?
> Proper Find Replace Search

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/views/main_view.py
- Turned filter on per default
- minor adjustments to tooltip
- added a spacer
- Filter now functional according to placeholder
> Filter adjustments

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/views/task_bar.py
I added a help taskbar, but it only points to the readthedocs. Mine automatically had a search function, so i did not specifically add this. Is this true for windows as well?
> Help Section

- src/petab_gui/controllers/table_controllers.py
- src/petab_gui/models/pandas_table_model.py
- src/petab_gui/utils.py
- Fixed finding previous
- Adapted matches to be highlighted
- Focusing when find_mec/previous but not when searching
More Ideas welcome
> Fix Search

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/views/main_view.py
- src/petab_gui/views/task_bar.py
Changed the syncing of the visibility and added a Resetview.
Wanted to have equal spacing, but that did not work out somehow.
> Reset View

- src/petab_gui/controllers/table_controllers.py
changed a bug in row deletion that only allow a single row deletion.
> Row Deletion

- src/petab_gui/app.py
this works fine on  windows ... does it do anything on the mac?
>  - set icon on application

- src/petab_gui/controllers/mother_controller.py
- src/petab_gui/views/simple_plot_view.py
When Sim_df is available, plot both residuals and Goodness of fit functions
> Residual Plot

- src/petab_gui/views/simple_plot_view.py
Only update plots if they are actually visible (+ update if visibility is toggled)
> Performance improvement in data plotting

- docs/source/conf.py
- docs/source/tutorial.rst
- src/petab_gui/commands.py
- src/petab_gui/models/pandas_table_model.py
Fixed an error with data matrix upload:
1. Tried to push empty default values
2. Did not correctly add the changes in measurement table as it is a non indexed table
> Data Matrix Upload

- src/petab_gui/models/petab_model.py
- src/petab_gui/settings_manager.py
Name, Email and Organization in General Settings. To be used (discussed in #104) in combine archive
> Credentials in Settings

- src/petab_gui/controllers/mother_controller.py
Renamed Save to "Save As" and added Ellipses to items that open a dialogue.
> Menu Items Conventions

- docs/source/contributing.rst
- tox.ini
Add contribution guide and add tox config for building docs.
@PaulJonasJost Please update as you wish.
> Contribution guide & tox for docs

- src/petab_gui/controllers/mother_controller.py
New File resets unsaved changes. Closes #150
> Unsaved Changes Updating

- .zenodo.json
Added ORCID for Daniel Weindl in .zenodo.json
- fixes #194
> Update .zenodo.json with new author ORCID

- src/petab_gui/views/simple_plot_view.py
> Fix cropped x-axis label in plots

- docs/source/tutorial.rst
Add cross references, fix typos, formatting.
> Prettify tutorial
