PEtab-dev/PEtab-GUI

src/petab_gui/views/main_view.py, src/petab_gui/views/task_bar.py
So ideally, we would have a toolbar with actions from the main menu. Currently some things are odd with it: 
- when the actions are initially created, they should have been created with icons / shortcuts 
since that didn't happen, the toolbar right now has really long names. 
I suggest, that we separate creating actions from adding them to menu / toolbars / controllers as discussed earlier today.
=> Add a toolbar to the application

src/petab_gui/views/main_view.py
Here is how i think settings should work:
- for now it only captures the application position on the screen
- the status of the dock window visibility
not quite sure why the position of the dock windows is not restored.
=> Settings start

src/petab_gui/models/petab_model.py, src/petab_gui/models/sbml_model.py
this PR fixes the issue of getting the current sbml model. 
Unfortunately warnings are interpreted as an error, would need latest libpetab from develop to work properly.
=>  - create sbmlmodel from string

src/petab_gui/controllers/mother_controller.py
Previously, when closing the DockWidget **within** the window (n ot through the taskbar) it did not update the toggle in the taskbar. Now it does
=> Fixed visibility button issue

src/petab_gui/C.py
Changed the default columns in condition to have at least on column (plus conditionId index). Fixes bug mentioned in #55
=> Empty Condition DF to have at least one column

src/petab_gui/utils.py
we need to read the file as unicode, since they might have unicode markers in there, which otherwise cause the file handling to make mistakes.
=>  - need to read as utf8

src/petab_gui/controllers/mother_controller.py, src/petab_gui/controllers/utils.py, src/petab_gui/utils.py, src/petab_gui/views/task_bar.py
Tracks the ten most recent files and enables opening them with overwrite
=> Enable Recent Files

src/petab_gui/views/main_view.py
Dont allow tabbing docks anymore, fixes invisibility problems. Fixes a bug where tabs vanished and could not be brought back anymore
=> Disallow Tabs in docks

src/petab_gui/controllers/mother_controller.py, src/petab_gui/controllers/table_controllers.py, src/petab_gui/models/pandas_table_model.py, src/petab_gui/utils.py, src/petab_gui/views/context_menu_mananger.py, src/petab_gui/views/table_view.py
Any additional features that might be good to have in a context menu?
=> First Draft for a context Menu

src/petab_gui/C.py, src/petab_gui/commands.py, src/petab_gui/controllers/default_handler.py, src/petab_gui/controllers/logger_controller.py, src/petab_gui/controllers/mother_controller.py, src/petab_gui/controllers/sbml_controller.py, src/petab_gui/controllers/table_controllers.py, src/petab_gui/controllers/utils.py, src/petab_gui/models/pandas_table_model.py, src/petab_gui/models/petab_model.py
Now possible to fill the parameter values from the sbml model
=> Default Values from SBML

.zenodo.json, README.md, pyproject.toml, setup.py, src/petab_gui/views/find_replace_bar.py
Should now have a zenodo integration together with a zenodo.json file
=> Zenodo Integration

src/petab_gui/C.py, src/petab_gui/commands.py, src/petab_gui/controllers/mother_controller.py, src/petab_gui/controllers/table_controllers.py, src/petab_gui/models/__init__.py, src/petab_gui/models/pandas_table_model.py, src/petab_gui/models/petab_model.py, src/petab_gui/utils.py, src/petab_gui/views/find_replace_bar.py, src/petab_gui/views/main_view.py, src/petab_gui/views/simple_plot_view.py, src/petab_gui/views/task_bar.py, src/petab_gui/views/utils.py
New plotter supports:
Plotting is run in the background and bunched together in case multiple things are changed simultaneously.
=> New Plotter

pyproject.toml, src/petab_gui/controllers/mother_controller.py, src/petab_gui/views/main_view.py, src/petab_gui/views/task_bar.py
Clicking simulation will replace the simulation dataframe with the one computed by basico / COPASI. It is only performing a current solution statistic (i.e comparing current simulation result with the measurement).
=> adds a simulation button to the gui

pyproject.toml
Dependencies should be listed under `project`, not under `project.license`. Installation of the current package on PyPI will not install any dependencies.
=> Fix project dependencies

src/petab_gui/controllers/utils.py
Fixed a bug that had the help-mode cursor not be reset. I blocked signals there.
=> Correct exit of Help-Mode

pyproject.toml
Fixes:
```
SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
```
=> Fix SetuptoolsDeprecationWarning / update license info

.github/workflows/ci.yml
The minimum testing we can do is checking that the GUI can be launched.
Closes #118
=> GHA: test app launch

.github/workflows/python-publish.yml, .readthedocs.yaml, README.md, docs/source/conf.py, docs/source/contributing.rst, docs/source/index.rst
* Full checkout for packaging
* Don't hardcode version for sphinx builds
* Fix README
* Add contributing.rst to docs
* Fix link
=> Fix setuptools-scm integration

README.md
* Refer to benchmark collection for examples
* `pipx` pointer
* PyPI version badge
=> README: add examples, pipx

.readthedocs.yaml, docs/source/conf.py, docs/source/index.rst
* Remove not-so-important setuptools config.
* Dynamic version number
=> Fix RTD build

README.md, pyproject.toml, src/petab_gui/C.py, src/petab_gui/app.py, src/petab_gui/controllers/mother_controller.py, src/petab_gui/views/main_view.py, src/petab_gui/views/task_bar.py
=> Add about dialog

README.md, docs/source/contributing.rst, docs/source/index.rst, docs/source/tutorial.rst, pyproject.toml, src/petab_gui/C.py
Update repository URLs after move.
Closes #145.
=> Update repository URLs

src/petab_gui/controllers/utils.py
Ensure that `petab_gui.controllers.utils.RecentFilesManager.load_recent_files` always returns a list of strings. It seems there is some serialization issue for `list[str]` of length 1 (sometimes?!). Fixes #122.
=> Fix recent files

src/petab_gui/commands.py, src/petab_gui/controllers/default_handler.py, src/petab_gui/controllers/mother_controller.py, src/petab_gui/controllers/table_controllers.py, src/petab_gui/models/pandas_table_model.py, src/petab_gui/settings_manager.py, src/petab_gui/views/simple_plot_view.py
- Now temporarily disables plotting while data is being set.
- additionally rename yValues when observable ID is renamed
Fixes #192 (for me)
=> Update Visualization Table on Changes

.zenodo.json, docs/source/conf.py, docs/source/index.rst
=> More renaming
